# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('estat', models.CharField(max_length=20)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('departament', models.ManyToManyField(to='CoInf.Departaments')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('quantitat', models.IntegerField(default=0)),
                ('caracteristiques', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Usuaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('cognoms', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('tipus', models.CharField(max_length=20)),
                ('contrasenya', models.CharField(max_length=64)),
                ('departament', models.ManyToManyField(to='CoInf.Departaments')),
            ],
        ),
        migrations.AddField(
            model_name='compres',
            name='departament',
            field=models.ManyToManyField(to='CoInf.Departaments'),
        ),
        migrations.AddField(
            model_name='compres',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CoInf.Material'),
        ),
    ]
