# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoInf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compres',
            name='quantitat',
            field=models.IntegerField(default=1),
        ),
    ]
