# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoInf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuaris',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
