# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoInf', '0002_compres_quantitat'),
    ]

    operations = [
        migrations.AddField(
            model_name='compres',
            name='pressupost',
            field=models.IntegerField(default=0),
        ),
    ]
