# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoInf', '0002_auto_20170424_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencies',
            name='descripcion',
            field=models.TextField(default='', max_length=400),
        ),
    ]
