# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoInf', '0003_compres_pressupost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencies',
            name='estat',
            field=models.CharField(default='oberta', max_length=20),
        ),
    ]
