# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoInf', '0003_auto_20170508_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compres',
            name='numero',
        ),
    ]
